// Module ID: 1177
// Function ID: 1178
// Name: native
// Dependencies: [1178, 1179, 2, 1180, 14348, 13599, 14349, 14352, 14353, 14354, 14355, 14356, 14357, 5115, 14358, 14360, 9844, 14361, 14362, 14364, 14365, 14366, 14367, 14368, 5188, 13319, 14377, 14379, 14359, 14381, 14383, 14384, 14385, 14386, 14387, 14388, 14389, 8889, 14390, 14453, 14454, 14455, 14456, 14457, 8888, 8870, 5334, 13725, 10010, 10527]

// Module 1177 (native)
import StatusConstants from "StatusConstants" /* 1178 */;
import BadgeConstants from "BadgeConstants" /* 1179 */;
import Button_Button from "Button/Button" /* 1180 */;
import OverlayView from "OverlayView" /* 5115 */;
import Icon from "Icon" /* 5188 */;
import Pressables from "Pressables" /* 5334 */;
import Form from "Form" /* 8870 */;
import CardSectionDefault from "CardSection" /* 8888 */;
import LegacyText_LegacyTextDefault from "LegacyText/LegacyText" /* 8889 */;
import TextInput_TextInputDefault from "TextInput/TextInput" /* 9844 */;
import TouchableHitBoxDefault from "TouchableHitBox" /* 10010 */;
import RoleLabel from "RoleLabel" /* 10527 */;
import CutoutableAvatarImage from "CutoutableAvatarImage" /* 13319 */;
import BetaTag from "BetaTag" /* 13599 */;
import IconButton_IconButton from "IconButton/IconButton" /* 13725 */;
import ShinyButton_ShinyButtonDefault from "ShinyButton/ShinyButton" /* 14348 */;
import Checkbox_CheckboxDefault from "Checkbox/Checkbox" /* 14349 */;
import CloseIconDefault from "CloseIcon" /* 14352 */;
import EllipsisDefault from "Ellipsis" /* 14353 */;
import GradientBorderDefault from "GradientBorder" /* 14354 */;
import HelpMessage from "HelpMessage" /* 14355 */;
import IconPillDefault from "IconPill" /* 14356 */;
import NewTagDefault from "NewTag" /* 14357 */;
import RadioGroup from "RadioGroup" /* 14358 */;
import CollapsibleDefault from "Collapsible" /* 14359 */;
import SummarizedIconRow from "SummarizedIconRow" /* 14360 */;
import ThemedIconDefault from "ThemedIcon" /* 14361 */;
import ThumbnailImageDefault from "ThumbnailImage" /* 14362 */;
import Tooltip_Tooltip from "Tooltip/Tooltip" /* 14364 */;
import WarningCircleDefault from "WarningCircle" /* 14365 */;
import Status_StatusUtils from "Status/StatusUtils" /* 14366 */;
import getStatusContainerStyleDefault from "getStatusContainerStyle" /* 14367 */;
import Status from "Status" /* 14368 */;
import Avatar from "Avatar" /* 14377 */;
import AccessibilityFocusViewDefault from "AccessibilityFocusView" /* 14379 */;
import PassthroughTouchViewDefault from "PassthroughTouchView" /* 14381 */;
import Easing from "Easing" /* 14383 */;
import SpacerDefault from "Spacer" /* 14384 */;
import LiveTagDefault from "LiveTag" /* 14385 */;
import RoleDot from "RoleDot" /* 14386 */;
import Shadows from "Shadows" /* 14387 */;
import NitroWheelDefault from "NitroWheel" /* 14388 */;
import EmptyStateDefault from "EmptyState" /* 14389 */;
import Atoms from "Atoms" /* 14390 */;
import Badge_Badge from "Badge/Badge" /* 14453 */;
import CarouselPaginationDefault from "CarouselPagination" /* 14454 */;
import InputView from "InputView" /* 14455 */;
import Badges_Badges from "Badges/Badges" /* 14456 */;
import RefreshEmptyState from "RefreshEmptyState" /* 14457 */;
import size from "module_2" /* 2 */;

const Button_ButtonDefault = Button_Button;
const OverlayViewDefault = OverlayView;
const IconDefault = Icon;
const CutoutableAvatarImageDefault = CutoutableAvatarImage;
const BetaTagDefault = BetaTag;
const HelpMessageDefault = HelpMessage;
const RadioGroupDefault = RadioGroup;
const SummarizedIconRowDefault = SummarizedIconRow;
const Tooltip_TooltipDefault = Tooltip_Tooltip;
const StatusDefault = Status;
const AvatarDefault = Avatar;
const Badge_BadgeDefault = Badge_Badge;
const InputViewDefault = InputView;
const RefreshEmptyStateDefault = RefreshEmptyState;

const result = size.fileFinishedImporting("design/void/native.tsx");

export const Button = Button_ButtonDefault;
export const BUTTON_CORNER_RADIUS = Button_Button.BUTTON_CORNER_RADIUS;
export const useButtonStyles = Button_Button.useButtonStyles;
export const ButtonLooks = Button_Button.ButtonLooks;
export const ButtonColors = Button_Button.ButtonColors;
export const ButtonSizes = Button_Button.ButtonSizes;
export const getButtonStyles = Button_Button.getButtonStyles;
export const ButtonText = Button_Button.ButtonText;
export const getRedesignVariant = Button_Button.getRedesignVariant;
export const getRedesignSize = Button_Button.getRedesignSize;
export const ShinyButton = ShinyButton_ShinyButtonDefault;
export const BetaTag = BetaTagDefault;
export const BetaSizes = BetaTag.BetaSizes;
export const Checkbox = Checkbox_CheckboxDefault;
export const CloseIcon = CloseIconDefault;
export const Ellipsis = EllipsisDefault;
export const GradientBorder = GradientBorderDefault;
export const HelpMessage = HelpMessageDefault;
export const HelpMessageTypes = HelpMessage.HelpMessageTypes;
export const IconPill = IconPillDefault;
export const NewTag = NewTagDefault;
export const OverlayView = OverlayViewDefault;
export const TransitionGroupOverlayView = OverlayView.TransitionGroupOverlayView;
export const NonExpandingOverlayView = OverlayView.NonExpandingOverlayView;
export const RadioGroup = RadioGroupDefault;
export const RadioIndicator = RadioGroup.RadioIndicator;
export const RadioItem = RadioGroup.RadioItem;
export const SummarizedIconRow = SummarizedIconRowDefault;
export const OverflowText = SummarizedIconRow.OverflowText;
export const OverflowTextSmall = SummarizedIconRow.OverflowTextSmall;
export const OverflowCircle = SummarizedIconRow.OverflowCircle;
export const TextInput = TextInput_TextInputDefault;
export const ThemedIcon = ThemedIconDefault;
export const ThumbnailImage = ThumbnailImageDefault;
export const Tooltip = Tooltip_TooltipDefault;
export const TooltipArrowDirections = Tooltip_Tooltip.TooltipArrowDirections;
export const TooltipArrowPositions = Tooltip_Tooltip.TooltipArrowPositions;
export const WarningCircle = WarningCircleDefault;
export const STATUS_PADDING = StatusConstants.STATUS_PADDING;
export const StatusSizes = StatusConstants.StatusSizes;
export const getAnimatedTypingTranslateX = Status_StatusUtils.getAnimatedTypingTranslateX;
export const getMobileStatusContainerRect = Status_StatusUtils.getMobileStatusContainerRect;
export const getStatusTypingDimensions = Status_StatusUtils.getStatusTypingDimensions;
export const getStatusContainerStyle = getStatusContainerStyleDefault;
export const Status = StatusDefault;
export const StatusWithTyping = Status.StatusWithTyping;
export const Icon = IconDefault;
export const IconSizes = Icon.IconSizes;
export const getIconSize = Icon.getIconSize;
export const getIconStyle = Icon.getIconStyle;
export const CutoutableAvatarImage = CutoutableAvatarImageDefault;
export const AvatarSizes = CutoutableAvatarImage.AvatarSizes;
export const AVATAR_SIZE_MAP = CutoutableAvatarImage.AVATAR_SIZE_MAP;
export const avatarStyles = CutoutableAvatarImage.styles;
export const CutoutDirection = CutoutableAvatarImage.CutoutDirection;
export const CutoutType = CutoutableAvatarImage.CutoutType;
export const Avatar = AvatarDefault;
export const getStatusSize = Avatar.getStatusSize;
export const AccessibilityFocusView = AccessibilityFocusViewDefault;
export const Collapsible = CollapsibleDefault;
export const PassthroughTouchView = PassthroughTouchViewDefault;
export const BADGE_SIZE = BadgeConstants.BADGE_SIZE;
export const BADGE_SIZE_UNREAD = BadgeConstants.BADGE_SIZE_UNREAD;
export const BADGE_PADDING = BadgeConstants.BADGE_PADDING;
export const BADGE_MASK_SIZE = BadgeConstants.BADGE_MASK_SIZE;
export const BADGE_MASK_UNREAD_SIZE = BadgeConstants.BADGE_MASK_UNREAD_SIZE;
export const STANDARD_EASING = Easing.STANDARD_EASING;
export const DECELERATED_EASING = Easing.DECELERATED_EASING;
export const Spacer = SpacerDefault;
export const LiveTag = LiveTagDefault;
export const RoleDot = RoleDot.RoleDot;
export const generateBoxShadowStyle = Shadows.generateBoxShadowStyle;
export const EIGHT_DP_ELEVATION_SHADOW_PARAMS = Shadows.EIGHT_DP_ELEVATION_SHADOW_PARAMS;
export const FOUR_DP_ELEVATION_SHADOW_PARAMS = Shadows.FOUR_DP_ELEVATION_SHADOW_PARAMS;
export const EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS = Shadows.EXPERIMENTAL_HIGH_ELEVATION_SHADOW_PARAMS;
export const NO_ELEVATION_SHADOW_PARAMS = Shadows.NO_ELEVATION_SHADOW_PARAMS;
export const NitroWheel = NitroWheelDefault;
export const EmptyState = EmptyStateDefault;
export const LegacyText = LegacyText_LegacyTextDefault;
export const RNTextInput = Atoms.RNTextInput;
export const Badge = Badge_BadgeDefault;
export const MaskedBadge = Badge_Badge.MaskedBadge;
export const CarouselPagination = CarouselPaginationDefault;
export const InputView = InputViewDefault;
export const ClearButtonVisibility = InputView.ClearButtonVisibility;
export const BadgeColors = Badges_Badges.BadgeColors;
export const TextBadge = Badges_Badges.TextBadge;
export const RefreshEmptyState = RefreshEmptyStateDefault;
export const ThemedEmptyState = RefreshEmptyState.ThemedEmptyState;
export const CardSection = CardSectionDefault;
export const Form = Form.Form;
export const FormArrow = Form.FormArrow;
export const FormCheckbox = Form.FormCheckbox;
export const FormCheckmark = Form.FormCheckmark;
export const FormCTA = Form.FormCTA;
export const FormCTAButton = Form.FormCTAButton;
export const FormDivider = Form.FormDivider;
export const FormHint = Form.FormHint;
export const FormIcon = Form.FormIcon;
export const FormInput = Form.FormInput;
export const FormLabel = Form.FormLabel;
export const FormRadio = Form.FormRadio;
export const FormRow = Form.FormRow;
export const FormSection = Form.FormSection;
export const FormSelect = Form.FormSelect;
export const FormSubLabel = Form.FormSubLabel;
export const FormSwitch = Form.FormSwitch;
export const FormText = Form.FormText;
export const FormTextColors = Form.FormTextColors;
export const FormTitle = Form.FormTitle;
export const FormSwitchRow = Form.FormSwitchRow;
export const FormRadioRow = Form.FormRadioRow;
export const FormCheckboxRow = Form.FormCheckboxRow;
export const FormRadioGroup = Form.FormRadioGroup;
export const FormSliderRow = Form.FormSliderRow;
export const FormCardSection = Form.FormCardSection;
export const PressableOpacity = Pressables.PressableOpacity;
export const PressableHighlight = Pressables.PressableHighlight;
export const SquareIconButton = IconButton_IconButton.SquareIconButton;
export const CircularIconButton = IconButton_IconButton.CircularIconButton;
export const TouchableHitBox = TouchableHitBoxDefault;
export const RoleLabel = RoleLabel.RoleLabel;
