// Module ID: 8459
// Function ID: 8460
// Name: Circle
// Dependencies: [8460, 8484, 8486, 8488, 8490, 8492, 8496, 8498, 8499, 8501, 8502, 8503, 8504, 8505, 8510, 8515, 8506, 8516, 8512, 8514, 8517, 8508, 8518, 8519, 8520, 8521, 8522, 8523, 8525, 8470, 8527, 8529, 8531, 8535, 8537, 8540, 8542, 8544, 8546, 8547, 8549, 8551, 8552, 8554, 8558, 8555, 8560]

// Module 8459 (Circle)
import _isNativeReflectConstructDefault from "_isNativeReflectConstruct" /* 8460 */;
import _isNativeReflectConstructDefault2 from "_isNativeReflectConstruct" /* 8470 */;
import _isNativeReflectConstructDefault3 from "_isNativeReflectConstruct" /* 8484 */;
import _isNativeReflectConstructDefault4 from "_isNativeReflectConstruct" /* 8486 */;
import _isNativeReflectConstructDefault5 from "_isNativeReflectConstruct" /* 8488 */;
import _isNativeReflectConstructDefault6 from "_isNativeReflectConstruct" /* 8490 */;
import _isNativeReflectConstructDefault7 from "_isNativeReflectConstruct" /* 8492 */;
import _isNativeReflectConstructDefault8 from "_isNativeReflectConstruct" /* 8496 */;
import _isNativeReflectConstructDefault9 from "_isNativeReflectConstruct" /* 8498 */;
import _isNativeReflectConstructDefault10 from "_isNativeReflectConstruct" /* 8499 */;
import _isNativeReflectConstructDefault11 from "_isNativeReflectConstruct" /* 8501 */;
import _isNativeReflectConstructDefault12 from "_isNativeReflectConstruct" /* 8502 */;
import _isNativeReflectConstructDefault13 from "_isNativeReflectConstruct" /* 8503 */;
import _isNativeReflectConstructDefault14 from "_isNativeReflectConstruct" /* 8504 */;
import _isNativeReflectConstructDefault15 from "_isNativeReflectConstruct" /* 8505 */;
import _isNativeReflectConstructDefault16 from "_isNativeReflectConstruct" /* 8506 */;
import _isNativeReflectConstructDefault17 from "_isNativeReflectConstruct" /* 8508 */;
import _isNativeReflectConstructDefault18 from "_isNativeReflectConstruct" /* 8510 */;
import _isNativeReflectConstructDefault19 from "_isNativeReflectConstruct" /* 8512 */;
import _isNativeReflectConstructDefault20 from "_isNativeReflectConstruct" /* 8514 */;
import _isNativeReflectConstructDefault21 from "_isNativeReflectConstruct" /* 8516 */;
import _isNativeReflectConstructDefault22 from "_isNativeReflectConstruct" /* 8517 */;
import _isNativeReflectConstructDefault23 from "_isNativeReflectConstruct" /* 8518 */;
import _isNativeReflectConstructDefault24 from "_isNativeReflectConstruct" /* 8519 */;
import _isNativeReflectConstructDefault25 from "_isNativeReflectConstruct" /* 8520 */;
import _isNativeReflectConstructDefault26 from "_isNativeReflectConstruct" /* 8521 */;
import _isNativeReflectConstructDefault27 from "_isNativeReflectConstruct" /* 8522 */;
import _isNativeReflectConstructDefault28 from "_isNativeReflectConstruct" /* 8523 */;
import _isNativeReflectConstructDefault29 from "_isNativeReflectConstruct" /* 8525 */;
import _isNativeReflectConstructDefault30 from "_isNativeReflectConstruct" /* 8527 */;
import _isNativeReflectConstructDefault31 from "_isNativeReflectConstruct" /* 8529 */;
import _isNativeReflectConstructDefault32 from "_isNativeReflectConstruct" /* 8531 */;
import _isNativeReflectConstructDefault33 from "_isNativeReflectConstruct" /* 8535 */;
import _isNativeReflectConstructDefault34 from "_isNativeReflectConstruct" /* 8537 */;
import _isNativeReflectConstructDefault35 from "_isNativeReflectConstruct" /* 8540 */;
import _isNativeReflectConstructDefault36 from "_isNativeReflectConstruct" /* 8542 */;
import _isNativeReflectConstructDefault37 from "_isNativeReflectConstruct" /* 8544 */;
import _isNativeReflectConstructDefault38 from "_isNativeReflectConstruct" /* 8546 */;
import _isNativeReflectConstructDefault39 from "_isNativeReflectConstruct" /* 8547 */;
import _isNativeReflectConstructDefault40 from "_isNativeReflectConstruct" /* 8549 */;
import _isNativeReflectConstructDefault41 from "_isNativeReflectConstruct" /* 8551 */;
import _isNativeReflectConstructDefault42 from "_isNativeReflectConstruct" /* 8552 */;
import _isNativeReflectConstructDefault43 from "_isNativeReflectConstruct" /* 8554 */;
import _isNativeReflectConstructDefault44 from "_isNativeReflectConstruct" /* 8555 */;
import _isNativeReflectConstructDefault45 from "_isNativeReflectConstruct" /* 8558 */;
import _isNativeReflectConstructDefault46 from "_isNativeReflectConstruct" /* 8560 */;


export default _isNativeReflectConstructDefault;
export const Circle = _isNativeReflectConstructDefault3;
export const ClipPath = _isNativeReflectConstructDefault4;
export const Defs = _isNativeReflectConstructDefault5;
export const Ellipse = _isNativeReflectConstructDefault6;
export const FeBlend = _isNativeReflectConstructDefault7;
export const FeColorMatrix = _isNativeReflectConstructDefault8;
export const FeComponentTransfer = _isNativeReflectConstructDefault9;
export const FeComposite = _isNativeReflectConstructDefault10;
export const FeConvolveMatrix = _isNativeReflectConstructDefault11;
export const FeDiffuseLighting = _isNativeReflectConstructDefault12;
export const FeDisplacementMap = _isNativeReflectConstructDefault13;
export const FeDistantLight = _isNativeReflectConstructDefault14;
export const FeDropShadow = _isNativeReflectConstructDefault15;
export const FeFlood = _isNativeReflectConstructDefault18;
export const FeFuncA = require("_isNativeReflectConstruct").FeFuncA;
export const FeFuncB = require("_isNativeReflectConstruct").FeFuncB;
export const FeFuncG = require("_isNativeReflectConstruct").FeFuncG;
export const FeFuncR = require("_isNativeReflectConstruct").FeFuncR;
export const FeGaussianBlur = _isNativeReflectConstructDefault16;
export const FeImage = _isNativeReflectConstructDefault21;
export const FeMerge = _isNativeReflectConstructDefault19;
export const FeMergeNode = _isNativeReflectConstructDefault20;
export const FeMorphology = _isNativeReflectConstructDefault22;
export const FeOffset = _isNativeReflectConstructDefault17;
export const FePointLight = _isNativeReflectConstructDefault23;
export const FeSpecularLighting = _isNativeReflectConstructDefault24;
export const FeSpotLight = _isNativeReflectConstructDefault25;
export const FeTile = _isNativeReflectConstructDefault26;
export const FeTurbulence = _isNativeReflectConstructDefault27;
export const Filter = _isNativeReflectConstructDefault28;
export const ForeignObject = _isNativeReflectConstructDefault29;
export const G = _isNativeReflectConstructDefault2;
export const Image = _isNativeReflectConstructDefault30;
export const Line = _isNativeReflectConstructDefault31;
export const LinearGradient = _isNativeReflectConstructDefault32;
export const Marker = _isNativeReflectConstructDefault33;
export const Mask = _isNativeReflectConstructDefault34;
export const Path = _isNativeReflectConstructDefault35;
export const Pattern = _isNativeReflectConstructDefault36;
export const Polygon = _isNativeReflectConstructDefault37;
export const Polyline = _isNativeReflectConstructDefault38;
export const RadialGradient = _isNativeReflectConstructDefault39;
export const Rect = _isNativeReflectConstructDefault40;
export const Stop = _isNativeReflectConstructDefault41;
export const Svg = _isNativeReflectConstructDefault;
export const Symbol = _isNativeReflectConstructDefault42;
export const Text = _isNativeReflectConstructDefault43;
export const TextPath = _isNativeReflectConstructDefault45;
export const TSpan = _isNativeReflectConstructDefault44;
export const Use = _isNativeReflectConstructDefault46;
